##############################
# Base docker image for SMVS #
# DO NOT RUN DIRECTLY        #
##############################

# Uses the go alpine image because it's small
FROM golang:1.16-alpine

ENV GO111MODULE=auto
ENV PATH /usr/local/go/bin:$PATH

WORKDIR /go/src/smvs
COPY . .

RUN apk add build-base bash
# Installs the smvs protos module
WORKDIR /go/src/smvs/protos
RUN go install github.com/AdamPayzant/COMP4109Project/src/protos/...

WORKDIR /go/src/smvs